_global.codeArray = new Array();
codeArray.push("0 - OK");
codeArray.push("100 - Continue");
codeArray.push("101 - Switching Protocols");
codeArray.push("200 - OK");
codeArray.push("201 - Created");
codeArray.push("202 - Accepted");
codeArray.push("203 - Non-Authoritative Information");
codeArray.push("204 - No Content");
codeArray.push("205 - Reset Content"); 
codeArray.push("206 - Partial Content");
codeArray.push("300 - Multiple Choices"); 
codeArray.push("301 - Moved Permanently"); 
codeArray.push("302 - Found"); 
codeArray.push("303 - See Other"); 
codeArray.push("304 - Not Modified"); 
codeArray.push("305 - Use Proxy"); 
codeArray.push("306 - No Longer Used"); 
codeArray.push("307 - Temporary Redirect"); 
codeArray.push("400 - Bad Request");
codeArray.push("401 - Not Authorised"); 
codeArray.push("402 - Payment Required"); 
codeArray.push("403 - Forbidden"); 
codeArray.push("404 - Not Found"); 
codeArray.push("405 - Method Not Allowed");
codeArray.push("406 - Not Acceptable"); 
codeArray.push("407 - Proxy Authentication Required");
codeArray.push("408 - Request Timeout"); 
codeArray.push("409 - Conflict"); 
codeArray.push("410 - Gone"); 
codeArray.push("411 - Length Required");
codeArray.push("412 - Precondition Failed"); 
codeArray.push("413 - Request Entity Too Large"); 
codeArray.push("414 - Request URI Too Long"); 
codeArray.push("415 - Unsupported Media Type"); 
codeArray.push("416 - Requested Range Not Satisfiable");
codeArray.push("417 - Expectation Failed"); 
codeArray.push("500 - Internal Server Error"); 
codeArray.push("501 - Not Implemented");
codeArray.push("502 - Bad Gateway"); 
codeArray.push("503 - Service Unavailable"); 
codeArray.push("504 - Gateway Timeout"); 
codeArray.push("505 - HTTP Version Not Supported");